# Generated by Django 3.2.12 on 2024-08-02 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentification', '0002_utilisateur_num_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='tache',
            name='predecesseurs',
            field=models.ManyToManyField(blank=True, related_name='successeurs', to='Authentification.Tache'),
        ),
    ]
