# Generated by Django 5.0.4 on 2024-08-07 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentification', '0005_ressource_prix_ressource_titre'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='fonction',
            field=models.CharField(default=0.0, max_length=150),
            preserve_default=False,
        ),
    ]
