# Generated by Django 5.0.4 on 2024-08-11 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentification', '0006_utilisateur_fonction'),
    ]

    operations = [
        migrations.AddField(
            model_name='tache',
            name='dateFin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tache',
            name='etat',
            field=models.IntegerField(choices=[(1, 'En attente'), (2, 'En cours'), (3, 'Terminé')], default=1),
        ),
        migrations.AddField(
            model_name='tache',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
    ]
