# Generated by Django 3.2.12 on 2024-08-12 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Authentification', '0007_tache_datefin_tache_etat_tache_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='tache',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Authentification.tache'),
            preserve_default=False,
        ),
    ]
